# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15U0DulYZwjMKh8Jt8-gzYZbr8NgxZgRb

**TITANIC SURVIVOR ANALYSIS**
"""

import pandas as pd
import numpy as np

"""READING DATA USING PANDAS

We use pandas read_csv function to read the csv file in python and pandas DataFrame method to convert file into the data frame.
"""

df = pd.DataFrame(pd.read_csv('/content/train (1).csv'))
df.head()

"""We use the shape function to find the number of rows and columns in the data frame."""

df.shape

df.shape[0]*35/100

"""HANDLING NULL VALUES

we use isnull() function to find the null values in the columns.
"""

df.isnull().sum()

"""
Seperating out the columns which have more than 35% of the values missing in the dataset"""

# df.isnull().sum() returns a pandas serise with columns name as the label index
# and total count of null values in the column as it's value
# and we are storing only those columns which have more than 35% of the data missing.

x = df.isnull().sum()

drop_col = x[x>(35/100 * df.shape[0])]
drop_col

drop_col.index

df.drop(drop_col.index, axis=1, inplace=True)
df.isnull().sum()

df.fillna(df.mean(), inplace=True)
df.isnull().sum()

"""The description of Embarked column shown in the following cod."""

df['Embarked'].describe()

"""We fill the NULL values in the Embarked column with the most frequent value 'S'"""

df['Embarked'].fillna('S',inplace=True)

df.isnull().sum()

df.corr()

"""We create a new column family_size by combining SibSp & Parch"""

df['FamilySize'] = df['SibSp']+df['Parch']
df.drop(['SibSp', 'Parch'], axis=1, inplace=True)
df.corr()

df['Alone'] = [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean()

df[['Alone','Fare']].corr()

df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index]  # 1 for female, 0 for male
df.groupby(['Sex'])['Survived'].mean()

df.groupby(['Embarked'])['Survived'].mean()

"""CONCLUSION

  If the person is alone he/she has less chance of surviving.

  Female passengers have more chance of surviving than male ones as women were prioritized over men.

  People with high class or rich pepole have higher survival rate than others. The hierarchy might hav been followed while the passengers.

  Passengers travelling with their family have higher survival rate.

  Passengers who boarded the ship Cherbourg, survived more in propotion than others.
"""